# colorscheme - solarized dark osaka
# Default colors
[colors.primary]
background = '#001a1d'
foreground = '#839496'

# Normal colors
[colors.normal]
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'

# Bright colors
[colors.bright]
black   = '#4c4c4c'
red     = '#cb4b16'
green   = '#586e75'
yellow  = '#657b83'
blue    = '#839496'
magenta = '#6c71c4'
cyan    = '#93a1a1'
white   = '#fdf6e3'

[font]
size = 15.0
normal = { family = "Terminess Nerd Font Mono", style = "Regular" }
bold = { family = "Terminess Nerd Font Mono", style = "Bold" }
italic = { family = "Terminess Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Terminess Nerd Font Mono", style = "Bold Italic" }


[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
opacity = 1
startup_mode = "maximized"
decorations_theme_variant = "Dark"

[env]
TERM = "xterm-256color"
