#!/usr/bin/env python3

import argparse
import datetime as dt
import json
import subprocess
import sys

from collections import defaultdict
from dataclasses import dataclass


@dataclass
class PullRequest:
    author: str
    url: str
    title: str
    merged_at: str

DATE_14D = (dt.datetime.now() - dt.timedelta(days=14))
GITHUB_ORGS = ['runreveal']

debug = False
active_repos = list()


def print_debug(msg: str):
    if debug:
        print(msg)


def parse_start_date(date: str) -> dt.datetime:
    try:
        return dt.datetime.fromisoformat(date)
    except Exception as e:
        print_debug(f'failed parsing date string: {e}')

    today_6pm = dt.datetime.now().replace(hour=18, minute=0, second=0)
    try:
        amount = int(date[0])
        time = 1 if date[1] == 'd' else 7 if date[1] == 'w' else 0

        parsed_date = (today_6pm - dt.timedelta(days=(amount * time)))
        print_debug(f'parsed date: {parsed_date.strftime("%Y %M %D %H:%M:%S")}')
        return parsed_date

    except Exception as e:
        print_debug(f'failed parsing date string: {e}')
        raise ValueError('unexpected date argument')


def get_active_repos() -> list[str]:
    for org in GITHUB_ORGS:
        cmd = subprocess.run(['gh', 'repo', 'list', org, '--limit', '200', '--no-archived', '--json', 'name,pushedAt,defaultBranchRef', '--jq', f'[.[] | select(.defaultBranchRef.name != "") | select(.pushedAt > "{DATE_14D.strftime("%Y-%m-%d")}") | .name]'],
                                capture_output=True, text=True)
        if cmd.returncode != 0:
            raise ValueError(f'failed getting list of errors: {cmd.stderr}')

        response = json.loads(cmd.stdout.strip())
        if 'status' in response and response['status'] != 200:
            raise ValueError(f"GitHub CLI command failed: {response['errors'][0]['message']}")

        active_repos.extend(response) 
    return active_repos


def get_merged_prs(date: dt.datetime) -> dict[str, dict[str, list[PullRequest]]]:
    now = dt.datetime.now()
    merged_prs: dict[str, dict[str, list[PullRequest]]] = defaultdict(lambda: defaultdict(list))

    if not active_repos:
        return merged_prs

    active_repo_set = set(active_repos)

    for org in GITHUB_ORGS:
        cmd = subprocess.run(['gh', 'api', '-X', 'GET', 'search/issues', '-f',
                                 f'q=org:{org} is:pr is:merged merged:{date.strftime("%Y-%m-%dT%H:%M:%SZ")}..{now.strftime("%Y-%m-%dT%H:%M:%SZ")}', '-F', 'per_page=100',
                                 '--jq', '.items[] | {repo: (.repository_url | split("/") | last), number, title, author: .user.login, url: .html_url, merged_at: .pull_request.merged_at}'],
                                 capture_output=True, text=True)
        if cmd.returncode != 0 and cmd.stderr != '':
            print(f'failed getting merged prs from {org}: {cmd.stderr}')
            continue

        if cmd.stdout == '':
            print_debug(f'{org} has no recent merges')
            continue

        for change in cmd.stdout.strip().split('\n'):
            response = json.loads(change)
            repo_name = response['repo']
            if repo_name in active_repo_set:
                merged_prs[org][repo_name].append(PullRequest(response['author'], response['url'], response['title'], response['merged_at']))

    return merged_prs


def pretty_print(merged_prs: dict[str, dict[str, list[PullRequest]]]):
    if not merged_prs:
        print('No merged PRs found in time window')
        return

    for org, repos in merged_prs.items():
        for repo, prs in repos.items():
            full_name = f'{org}/{repo}'
            spacer = '-' * len(full_name)
            print(f'{spacer}\n{full_name}\n{spacer}\n')

            if len(prs) == 0:
                print('\t No merged in time window')
                continue

            for pr in prs:
                print(f'\t * [{pr.merged_at}] {pr.title} ({pr.author}) - {pr.url}')

            print('\n')


def check_requirements():
    status = subprocess.run(['gh', 'status'], shell=True, capture_output=True)
    if status.returncode != 0:
        raise ValueError("gh status didn't work - either not logged in or gh not installed")


def main():
    parser = argparse.ArgumentParser(prog='ChangesViewer',
                                     description='Fetches changes from defined orgs in const GITHUB_ORGS',
                                     epilog='Made by gsilvapt')
    parser.add_argument('start_date', help='starting date to look for changes - 2d, 2w (defaults to previous day at 6pm)', nargs='?', default='1d')
    parser.add_argument('-d', '--debug', help='set debugging mode on, printing steps along the way')
    args = parser.parse_args()

    print_debug('parsing args')
    try:
        date = parse_start_date(args.start_date)
    except ValueError:
        args.print_help()
        sys.exit(1)
    
    try:
        check_requirements()
    except ValueError as e:
        print(e)
        sys.exit(1)

    active_repos = get_active_repos()
    merged_prs = get_merged_prs(date)
    pretty_print(merged_prs)

    sys.exit(0)


if __name__=='__main__': 
    main()
